import { eventHandler } from 'h3';
import { verifyAccessToken } from '~/utils/jwt-utils';
import { unAuthorizedResponse, useResponseSuccess } from '~/utils/response';

const mockResourceTree = [
  {
    id: 1,
    resourceName: '系统管理',
    parentId: 0,
    sort: 1,
    path: '/system',
    component: 'LAYOUT',
    resourceType: 'M',
    perms: '',
    icon: 'lucide:settings',
    status: 1,
    sys001: '2026-01-01 00:00:00',
    sys002: '2026-01-01 00:00:00',
    children: [
      {
        id: 2,
        resourceName: '用户管理',
        parentId: 1,
        sort: 1,
        path: 'user',
        component: '/system/user/list',
        resourceType: 'A',
        perms: 'system:user:list',
        icon: 'lucide:user',
        status: 1,
        sys001: '2026-01-01 00:00:00',
        sys002: '2026-01-01 00:00:00',
        children: [
          {
            id: 10,
            resourceName: '用户新增',
            parentId: 2,
            sort: 1,
            path: '',
            component: '',
            resourceType: 'F',
            perms: 'system:user:add',
            icon: '',
            status: 1,
            sys001: '2026-01-01 00:00:00',
            sys002: '2026-01-01 00:00:00',
          },
          {
            id: 11,
            resourceName: '用户修改',
            parentId: 2,
            sort: 2,
            path: '',
            component: '',
            resourceType: 'F',
            perms: 'system:user:edit',
            icon: '',
            status: 1,
            sys001: '2026-01-01 00:00:00',
            sys002: '2026-01-01 00:00:00',
          },
          {
            id: 12,
            resourceName: '用户删除',
            parentId: 2,
            sort: 3,
            path: '',
            component: '',
            resourceType: 'F',
            perms: 'system:user:remove',
            icon: '',
            status: 1,
            sys001: '2026-01-01 00:00:00',
            sys002: '2026-01-01 00:00:00',
          },
        ],
      },
      {
        id: 3,
        resourceName: '部门管理',
        parentId: 1,
        sort: 2,
        path: 'dept',
        component: '/system/dept/list',
        resourceType: 'A',
        perms: 'system:dept:list',
        icon: 'lucide:building',
        status: 1,
        sys001: '2026-01-01 00:00:00',
        sys002: '2026-01-01 00:00:00',
        children: [
          {
            id: 20,
            resourceName: '部门新增',
            parentId: 3,
            sort: 1,
            path: '',
            component: '',
            resourceType: 'F',
            perms: 'system:dept:add',
            icon: '',
            status: 1,
            sys001: '2026-01-01 00:00:00',
            sys002: '2026-01-01 00:00:00',
          },
          {
            id: 21,
            resourceName: '部门修改',
            parentId: 3,
            sort: 2,
            path: '',
            component: '',
            resourceType: 'F',
            perms: 'system:dept:edit',
            icon: '',
            status: 1,
            sys001: '2026-01-01 00:00:00',
            sys002: '2026-01-01 00:00:00',
          },
          {
            id: 22,
            resourceName: '部门删除',
            parentId: 3,
            sort: 3,
            path: '',
            component: '',
            resourceType: 'F',
            perms: 'system:dept:remove',
            icon: '',
            status: 1,
            sys001: '2026-01-01 00:00:00',
            sys002: '2026-01-01 00:00:00',
          },
        ],
      },
      {
        id: 4,
        resourceName: '角色管理',
        parentId: 1,
        sort: 3,
        path: 'role',
        component: '/system/role/list',
        resourceType: 'A',
        perms: 'system:role:list',
        icon: 'lucide:shield',
        status: 1,
        sys001: '2026-01-01 00:00:00',
        sys002: '2026-01-01 00:00:00',
        children: [
          {
            id: 30,
            resourceName: '角色新增',
            parentId: 4,
            sort: 1,
            path: '',
            component: '',
            resourceType: 'F',
            perms: 'system:role:add',
            icon: '',
            status: 1,
            sys001: '2026-01-01 00:00:00',
            sys002: '2026-01-01 00:00:00',
          },
          {
            id: 31,
            resourceName: '角色修改',
            parentId: 4,
            sort: 2,
            path: '',
            component: '',
            resourceType: 'F',
            perms: 'system:role:edit',
            icon: '',
            status: 1,
            sys001: '2026-01-01 00:00:00',
            sys002: '2026-01-01 00:00:00',
          },
          {
            id: 32,
            resourceName: '角色删除',
            parentId: 4,
            sort: 3,
            path: '',
            component: '',
            resourceType: 'F',
            perms: 'system:role:remove',
            icon: '',
            status: 1,
            sys001: '2026-01-01 00:00:00',
            sys002: '2026-01-01 00:00:00',
          },
        ],
      },
      {
        id: 5,
        resourceName: '资源管理',
        parentId: 1,
        sort: 4,
        path: 'resource',
        component: '/system/resource/list',
        resourceType: 'A',
        perms: 'system:resource:list',
        icon: 'lucide:menu',
        status: 1,
        sys001: '2026-01-01 00:00:00',
        sys002: '2026-01-01 00:00:00',
        children: [
          {
            id: 40,
            resourceName: '资源新增',
            parentId: 5,
            sort: 1,
            path: '',
            component: '',
            resourceType: 'F',
            perms: 'system:resource:add',
            icon: '',
            status: 1,
            sys001: '2026-01-01 00:00:00',
            sys002: '2026-01-01 00:00:00',
          },
          {
            id: 41,
            resourceName: '资源修改',
            parentId: 5,
            sort: 2,
            path: '',
            component: '',
            resourceType: 'F',
            perms: 'system:resource:edit',
            icon: '',
            status: 1,
            sys001: '2026-01-01 00:00:00',
            sys002: '2026-01-01 00:00:00',
          },
          {
            id: 42,
            resourceName: '资源删除',
            parentId: 5,
            sort: 3,
            path: '',
            component: '',
            resourceType: 'F',
            perms: 'system:resource:remove',
            icon: '',
            status: 1,
            sys001: '2026-01-01 00:00:00',
            sys002: '2026-01-01 00:00:00',
          },
        ],
      },
    ],
  },
];

export default eventHandler(async (event) => {
  const userinfo = verifyAccessToken(event);
  if (!userinfo) {
    return unAuthorizedResponse(event);
  }

  return useResponseSuccess(mockResourceTree);
});
